# Set if clay blocks can be turned into 4 clay balls
clay-conversion: true

# Set if stone tools should be craftable via the stone variants
# (i.e. diorite, andesite, granite can all be used to craft stone tools)
stone-tool-variant: true

# Can players edit signs by right-clicking on them with an empty hand
editable-signs: true

# Can users convert dirt to grass paths?
dirt-to-path: true

# Can players right click with a shovel and shave a layer of snow off of snow blocks?
shave-snow: true

# Can sponges become dry in the nether?
sponge:
  enabled: true
  # The chance this sponge will dry in the nether.
  # This value means the sponge will have a 1 in 'X' chance to become dry
  dry-chance: 7

minecart:
  # Can users modify minecarts by right clicking on them with the appropriate blocks
  # (i.e. right clicking with a chest will produce a minecart chest)
  modification: true
  # Set the stack size for minecarts
  stack-size: 16

armor-stand:
  # Armor Stands will add arms when shift right-clicked with a stick
  add-arms: true
  # Armor Stands will remove the base plate when shift right-clicked with a pair of shears
  hide-base-plate: true
  # Armor Stands will add the base plate(if removed) when shift right-clicked with a stone slab
  add-base-plate: true
  # Can players quickly swap all armor quickly.
  quick-swap: true
  # Will the offhand slot get swapped as well
  offhand-swap: true

# This will also suppress all chat to the console! Use this with extreme caution!
# There are no guarantees that chat will be logged if this is true.
suppress-output:
  # Will this plugin suppress any STDOUT  messages that are output by other plugins
  stdout: false
  #Will this plugin suppress any STDERR message that are output by other plugins
  stderr: false

# Will baby zombies burn in the sunlight
burn-baby-zombies:
  enabled: true
  # How long the baby zombies will burn for (in seconds)
  # Zombies will be re-checked after this length to see if they should still be burning
  length: 1

# Changes the dragon breath crafting recipe result to nothing.
# Fixes the issue of using dragon's breath in brewing stands
fix-dragon-breath: true

villagers:
  # Should villagers follow players with the specified item
  enabled: true
  # What block villagers should follow
  # This is the default minecraft name of the item
  follow-block: emerald_block

# This section dictates how certain enchantments work
enchantment:
  tree_feller:
    # Add this enchantment or not
    # This will only take effect on restarts and the behaviour is undefined if the enchantment was
    # already on items
    enabled: true
    # If blocks break sounds should not be played when this enchantment takes effect
    muted: false
    # Does this enchantment require the player is sneaking to activate?
    require-sneaking: false
    # How often a block should be broken, in ticks
    period: 5
    # Should this enchantment ignore log variants when looking at a tree
    ignore_log_variants: false
    # Should this enchantment ignore leaf variants when looking a a tree
    ignore_leaf_variants: false
# Will display all settings on loading
verbose: false