name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${author}
main: ${main.Class}
load: POSTWORLD
commands:
  vt:
    description: Main command for the VanillaTweaks plugin
